- title: 'graduate representative'
  description: 'elected liason between graduate student body and faculty; plan student-facing and external events including interview weekend'
  year: '2020-2021 academic year'

- title: 'diversity and inclusion action plan (diap) student representative'
  description: 'elected advocate for the graduate student body’s interests and concerns on the diap committee and with the graduate program leadership'
  year: '2021-2022 academic year'

- title: 'committee member - clps diap'
  year: '2020- present'
  description: 'work on curriculum subcommittee to assess and improve the curriculum of clps department courses through planning reading groups, syllabi surveys, and developing new courses'
