- title: 'Diversity and Inclusion Action Plan, CLPS Department'
  name: 'Committee Member'
  locdate: 'Brown University, 2020-Present'
  info: 'Work on Curriculum Subcommittee to assess and improve the curriculum of CLPS Department courses through planning reading groups, syllabi surveys, and workshops on difficult topics in teaching.'

- title: 'Undergraduate Curriculum Committee, CLPS Department'
  name: 'Elected Graduate Liason'
  locdate: 'Brown University, 2023-2024 Academic Year'
  info: 'Elected as departmental graduate student representative to serve on the faculty undergraduate curriculum committee to discuss coursework, honors requirements, curriculum needs, and majors offered by the department.'

- title: 'College Day at Brown'
  name: 'Discipline Activity Organizer'
  locdate: 'Carney Institute at Brown University, 2023 & 2024'
  info: 'Proposed, organized, and led neuroscience activities for local high school students to encourage them in pursuit of higher education.'
  link: 'https://www.brown.edu/news/2023-04-06/collegeday'

- title: 'Brown Brain Fair'
  name: 'Lab Ambassador'
  locdate: 'Brown University, 2023 & 2024'
  info: 'Organized activity table to explore brain function with local community members as a part of Brain Waves RI.'

- title: 'Elementary School Field Trips, Carney Institute at Brown University'
  name: 'Activity Leader'
  locdate: '2023'
  info: 'Assisted with two outreach events to engage local elementary school students with psychology and neuroscience activities.'

- title: 'Leadership Alliance National Symposium'
  name: 'Brown University Ambassador'
  locdate: '2022'
  info: 'Presented information on Brown University graduate programs and answered potential student questions.'

- title: 'Diversity and Inclusion Liaison, CLPS Department'
  name: 'Elected Graduate Representative'
  locdate: 'Brown University, 2021-2022 Academic Year'
  info: 'Elected as departmental representative to bring diversity and inclusion related issues to faculty, and implement departmental trainings and workshops as necessary.'

- title: 'Graduate Outreach Panel, CLPS Department'
  name: 'Organizer'
  locdate: 'Brown University, Fall 2021'
  info: 'Organized panel to answer questions about graduate training in our department targeted at students from schools that are traditionally underrepresented in our applicant pool. Coordinated program advertisement with advising staff at nationwide universities for successful online event.'

- title: 'Diversity and Inclusion Reading Group, CLPS Department'
  name: 'Organizer'
  locdate: 'Brown University, 2021-present'
  info: 'Founded and organize yearly three-book reading and discussion series on racism and discrimination in psychology.'

- title: 'International Student Orientation'
  name: 'Peer Mentor'
  locdate: 'Brown University, 2021-2024'
  info: 'Served as peer mentor to incoming international graduate students during orientation.'

- title: 'Careers Outside Academia Series, CLPS Department'
  name: 'Organizer'
  locdate: 'Brown University, 2020-2021 Academic Year'
  info: 'Organized and hosted talk series open to undergraduates, graduate students, and postdocs across CLPS and Neuroscience departments featuring alumni who pursued careers outside of traditional academia.'

- title: 'Graduate Representative, CLPS Department'
  name: 'Elected Graduate Student'
  locdate: 'Brown University, 2020-2021 Academic Year'
  info: 'Elected as one of two departmental representatives of graduate student body. Serve to bring student ideas and concerns to faculty and plan events like town-hall meetings, socials, and professional development seminars.'
