- title: 'graduate representative'
  description: 'elected liason between graduate student body and faculty; plan student-facing and external events including interview weekend'
  year: '2020-2021 school year'

- title: 'diversity and inclusion action plan student representative'
  description: 'elected'
